micronaut:
  codec:
    json:
      additionalTypes:
        - text/javascript
  application:
    name: itapilog
  http:
    client:
      exception-on-error-status: false
    services:
      exception-on-error-status: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/*
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
integration:
  viacep:
    url: http://viacep.com.br
mongodb.uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:miclog}?authSource=admin

